version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y postgresql-client &&
        until pg_isready; do sleep 1; done;
        exec bash"
